version: 2
jobs:
  retrieve:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Pull Dependencies
          command: npm install
      - run:
          name: Build Client Side
          command: (cd ./client && ../node_modules/webpack/bin/webpack.js --colors)
      - run:
          name: Build Server Side
          command: cp -R ./server/* ./dist
      - run:
          name: package.json
          command: cp ./package*.json ./dist
      - run:
          name: Package zip for S3
          command: (cd ./dist && zip -r /tmp/server.zip ./*)
