version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - npm-{{ checksum "package-lock.json" }}
            - run:
                name: Pull Dependencies
                command: npm install
            - save_cache:
                key: npm-{{ checksum "package-lock.json" }}
                paths:
                    - "~/project/node_modules"
            - run:
                name: Build Client Side
                command: (cd ./client && ../node_modules/webpack/bin/webpack.js --colors)
            - run:
                name: Build Server Side
                command: cp -R ./server/* ./dist
            - run:
                name: package.json
                command: cp ./package*.json ./dist
            - run:
                name: Package zip for S3
                command: (cd ./dist && zip -r /tmp/server.zip ./*)
            - persist_to_workspace:
                root: /tmp
                paths:
                    server.zip
    deploy:
        docker:
            - image: circleci/python:2.7-jessie
        steps:
            - run:
                name: Install awscli
                command: sudo pip install awscli
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: Deploy to S3
                command: aws s3 cp --region us-east-1 /tmp/workspace/server.zip s3://my-portfolio-deploy

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                # filters:
                #     branches:
                #         only: master