source 'https://supermarket.chef.io'

metadata

cookbook 'nodejs', '~> 3.0.0'
cookbook 'magic_shell'
cookbook 'cron', '~> 1.7.6'
cookbook 'monit', git: 'https://github.com/phlipper/chef-monit.git'
cookbook 'aws', '~> 3.4.1'

cookbook 'main', path: './site-cookbooks/main'
