Vagrant.configure("2") do |config|
    config.vm.hostname = "dev"
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "forwarded_port", guest: 3000, host: 3000, protocol: "tcp"
    config.vm.network "forwarded_port", guest: 3001, host: 3001, protocol: "tcp"
    config.vm.synced_folder "../", "/srv/www", fsnotify: true

    config.nfs.map_uid = Process.uid
    config.nfs.map_gid = Process.gid

    config.omnibus.chef_version = "12.19.36"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "my-portfolio"
        vb.memory = "2048"

        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = "./Berksfile"

    config.vm.provision "chef_zero" do |chef|
        chef.cookbooks_path = ['cookbooks', 'site-cookbooks']
        chef.data_bags_path = "data_bags"
        chef.nodes_path = "nodes"
        chef.roles_path = "roles"

        chef.encrypted_data_bag_secret_key_path = "../encrypted_data_bag_secret"

        chef.add_recipe "main::dev"
    end

    config.trigger.after :up do |trigger|
        trigger.info = "Starting fsnotify"
        trigger.run = {inline: "vagrant fsnotify"}
    end
end
