Vagrant.configure("2") do |config|
    config.vm.hostname = "dev"
    config.vm.box = "ubuntu/xenial64"
    config.vm.network "private_network", ip: "192.168.255.100"
    config.vm.synced_folder "../", "/home/ubuntu/my-portfolio", type: "nfs", mount_options: ['nolock,vers=3,udp,noatime,actimeo=1']

    config.nfs.map_uid = Process.uid
    config.nfs.map_gid = Process.gid

    config.omnibus.chef_version = "12.19.36"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "my-portfolio"
        vb.memory = "1024"

        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = "./Berksfile"

    config.vm.provision "chef_zero" do |chef|
        chef.cookbooks_path = ['cookbooks', 'site-cookbooks']
        chef.data_bags_path = "data_bags"
        chef.nodes_path = "nodes"
        chef.roles_path = "roles"

        # chef.encrypted_data_bag_secret_key_path = "../encrypted_data_bag_secret"

        chef.add_recipe "main::dev"
    end
end
