Vagrant.configure("2") do |config|
    config.vm.hostname = "dev"
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.synced_folder "../", "/home/vagrant/my-portfolio"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "my-portfolio"
        vb.memory = "1024"
    end

    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = "./Berksfile"

    config.notify_forwarder.enable = false

    config.vm.provision "chef_zero" do |chef|
        chef.cookbooks_path = ['cookbooks', 'site-cookbooks']
        chef.data_bags_path = "data_bags"
        chef.nodes_path = "nodes"
        chef.roles_path = "roles"

        chef.encrypted_data_bag_secret_key_path = "../encrypted_data_bag_secret"

        chef.add_recipe "main::dev"
    end
end
